version: '3.9'

services:
  frontend:
    build:
      context: ./frontend-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-app:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
